src/core/config.c, src/core/main.c, src/screencast/screencast_common.c
`service_name` in `main.c` file needs to be changed so dbus would recognize the service in xdg-desktop-portal.  Otherwise it stucks on `activating` (and timeouts eventually) because a service with such a name does not appear.
=> Change from wlr to hyprland so dbus would recognize

nix/default.nix
The portal needs `grim` and `slurp` in `PATH` to enable support for screenshots.
This PR adds these for the nix package
=> nix: adds grim and slurp to PATH to support screenshots

contrib/systemd/xdg-desktop-portal-hyprland.service.in
Consider xdg-desktop-portal-hyprland as essential for user's graphic session
See https://systemd.io/DESKTOP_ENVIRONMENTS/
=> systemd: switch slice for xdph

src/globalshortcuts/global_shortcuts.c
Regressed by #35 + https://github.com/llvm/llvm-project/commit/7068aa98412a
=> Unbreak build with Clang 15

meson.build, src/core/utils.c
Implicitly declared functions result only in a warning on GCC<=13 and clang<=16. However, starting with clang16 and probably also GCC14 once it is released -Wimplicit-function-declaration will be the default setting and the call of vasprintf will result in an error.
=> fix implicit function declaration

src/screencast/pipewire_screencast.c
Fixes my issue #71 
It seems like on line [325](https://github.com/nik012003/xdg-desktop-portal-hyprland/blob/4001b8a081c59ce84386cd9a8485c03e89affe87/src/screencast/pipewire_screencast.c#L325) there was an assigment to `params[3]` which is out of bounds. This undefined behaviour causes problems on aarch64. 
WARNING: I only tested this on aarch64, since I don't have an x86 box laying around, but it shouldnt cause any issues. 
Btw there are a few other problems on aarch64 due to rouge pointer comparaisons, which I will try to address in the next PR.
=> screencast: correct array size

flake.lock, flake.nix, nix/overlays.nix
1. The `nix fmt` command did not work for me so I have reverted it to use `legacyPackages` for simplicity. It works now.
2. Before there was one `default` overlay, which would make it hard to get individual packages out from the overlay. Would need an extra wrapper function. Now each package has its own overlay, while `default` combines them all. Brought in `mkJoinedOverlays` from the Hyprland flake.
- ```nix
$ nix eval 'path:.#overlays' --apply 'builtins.attrNames'
[ "default" "hyprland-share-picker" "xdg-desktop-portal-hyprland" ]
```
3. Moved `version` into `nix/overlays.nix`.
- Perhaps we should adopt my (unpublished) changes from `Alexays/Waybar` and pull the first version fragment from `meson.build`.
5. Added another input `nix-systems` so that the `systems` is overrideable. I like …
=> Nix: Some corrections for overlays

flake.lock, flake.nix
Depending on <https://github.com/hyprwm/hyprland-protocols/pull/6>, which is a blocker. Do not merge!
When that PR has been merged, must run:
```sh
nix flake lock --update-input hyprland-protocols
```
=> Nix: Inputs with `systems` follow this flake's `systems`

src/shared/ScreencopyShared.cpp
This pr will add an escape char for double quote in the window title string
- issue 
```txt
[LOG] [screencopy] SelectSources:
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/request/1_56507/obs2
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/session/1_56507/obs1
[LOG] [screencopy]  | appid:
[LOG] [screencopy] option cursor_mode to 2
[LOG] [screencopy] option persist_mode to 2
[LOG] [screencopy] unused option multiple
[LOG] [screencopy] unused option types
[LOG] [screencopy] restore data invalid / missing, prompting
[LOG] execAndGet: WAYLAND_DISPLAY=wayland-1 QT_QPA_PLATFORM="wayland" XCURSOR_SIZE=24 HYPRLAND_INSTANCE_SIGNATURE=d126d2c09204a09b0b10ce4f999520fc901fbf0a_1694861673 XDPH_WINDOW_SHARING_LIST="3451312672[HC>]Alacritty[HT>]./build/xdg-desktop-portal-hyprland[HE>]34513 …
```
=> feat: add double quote escaping

meson.build, src/core/PortalManager.cpp, src/portals/Screencopy.cpp
This PR is  addressing the failing build with clang as described in #81.
To fix the build with clang i added the flag -Wno-address-of-temporary to allow taking temporary addresses as the already existing -fpermissive flag does for gcc.
Furthermore i made some implicit typecasts  explicit that are accepted by gcc but not by clang.
The macro wl_array_for_each, used in PortalManager.cpp, which comes from wayland-utils, had to be implemented inline as it does depend on an implicit typecast that clang does not accept.
If this PR is merged the project can be built with clang and gcc using GNU libstdc++.
I did not test other stdlib implementations.
=> Fix build when using clang

src/core/PortalManager.cpp
The line #249 calls system bus by default, dbus will deny this request, then we need to call session bus instead.
=> Fix issue #114

nix/default.nix
Default build type is `plain`, we want to use `release`.
=> nix: default meson build type to release

hyprland.portal, src/core/PortalManager.cpp, src/core/PortalManager.hpp, src/helpers/MiscFunctions.cpp, src/helpers/MiscFunctions.hpp, src/portals/Screenshot.cpp, src/portals/Screenshot.hpp
Added back the screenshot functionality by using grim and slurp under the hood.
includes all functions from `org.freedesktop.impl.portal.Screenshot` (Screenshot, PickColor)
Fixes: #124
=> Added back screenshot functionality

src/portals/Screencopy.cpp
The current implementation never closes PipeWire streams after their sessions are closed. This PR adds a call to `destroyStream` to `session->onDestroy`.
I also made changes to `destroyStream` because it seems to reenter itself and cause a double free.
=> Destroy pipewire streams when ScreenCast sessions are closed

CMakeLists.txt
Addes Wno-address-of-temporary to cmake to fix clang build errors.
This is only necessary for cmake, as the flag is already present in meson.build
This should close #134
=> Fix build for clang

CMakeLists.txt
- Cmake: Do not use CMAKE_INSTALL_LIBDIR for the systemd service
- cmake: Don't install sdbus-cpp files
=> cmake fixes

hyprland-share-picker/main.cpp, hyprland-share-picker/mainpicker.ui
I just adjusted the picker to be resizable
And now buttons dont use absolute positions
I have limited c++ and qt knowledge but not able to resize that dialog was driving me crazy
=> picker: Allow dialog resizing

hyprland-share-picker/CMakeLists.txt, hyprland-share-picker/elidedbutton.cpp, hyprland-share-picker/elidedbutton.h, hyprland-share-picker/main.cpp, hyprland-share-picker/mainpicker.ui
It also fixes the region button size and alignment
fixes [#175](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/175#issuecomment-1913815879)
The reason of this PR is because i was having elided text in buttons because my theme
Now the elided text in buttons is on purpose
Before: See second element (image taken from #175)    
After:    
Ignore the theme, i forgot to take screenshot before doing the work
=> picker: Adds elided buttons for better readability

hyprland-share-picker/main.cpp
Fixes invalid screen name when text is elided
=> picker: Save the output name to a proper variable instead of parsing it from the button text

src/portals/Screencopy.cpp
Regressed by https://github.com/Kistler-Group/sdbus-cpp/commit/6e348f3910c5
=> Unbreak build with sdbus-cpp 1.5.0

src/core/PortalManager.cpp
ensure the screenshot portal is destructed before the connection is down, otherwise it segfaults inside sdbus.
fixes #208
=> core: reset screenshot pointer aswell

src/helpers/MiscFunctions.cpp
In certain unusual scenarios where the $PATH starts or contains a directory inaccessible to the user, running "/usr/lib/xdg-desktop-portal-hyprland" may produce the following error:
```
#PATH=/root/.local/bin:/root/go/bin:/home/v3llocet/.local/bin...
what(): filesystem error: status: Permission denied [/root/.local/bin/grim]
/home/v3llocet/.config/hypr/xdg: line 7: 6807 Aborted (core dumped) /usr/lib/xdg-desktop-portal-hyprland
```
This error occurs because the function "std::filesystem::exists" breaks when encountering such an error. To address this issue, I propose replacing it with "access" which can verify permissions and return true if the executable exists.
=> fix : inShellPath, Permission denied

src/portals/Screencopy.cpp
When the timer is less than 6 milliseconds, the screen copy portal would frequently fail to start working.
Fixes https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/225
Fixes https://github.com/hyprwm/Hyprland/issues/6396
=> screen copy: clamp the timer to a miminum of 6 milliseconds

src/portals/GlobalShortcuts.cpp, src/portals/GlobalShortcuts.hpp
hyprland_global_shortcuts_manager_v1_register_shortcut will cause an error if the (app_id, shortcut_id) combination has already been registered. Ignore shortcuts that have already been registered.
When a shortcut is registered again it should also overwrite the session for the keybind to make the shortcut work after restarting an application, otherwise the key can't be used again.
Fixes #236
=> global shortcuts: fix crash by ignoring duplicate shortcuts

src/portals/Screencopy.cpp, src/portals/Screencopy.hpp
Very hacky fix to make screencopy continue capturing frames after `Out of buffers` error occurs.
PR as requested in #247
=> hacky fix for fixing output screencopy

CMakeLists.txt
Otherwise after https://github.com/NixOS/nixpkgs/pull/214906 you get:
```
xdg-desktop-portal-hyprland> CMake Error in CMakeLists.txt:
xdg-desktop-portal-hyprland>   Imported target "PkgConfig::deps" includes non-existent path
xdg-desktop-portal-hyprland>     "/nix/store/0ikl83z4h69imxkwsly3hcm424f7wi7j-wayland-scanner-1.23.0-dev/include"
xdg-desktop-portal-hyprland>   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
xdg-desktop-portal-hyprland>   * The path was deleted, renamed, or moved to another location.
xdg-desktop-portal-hyprland>   * An install or uninstall procedure did not complete successfully.
xdg-desktop-portal-hyprland>   * The installation package was faulty and references files it does not
xdg-desktop-portal-hyprland>   provide.
```
=> CMakeLists: just search for the wayland-scanner binary

CMakeLists.txt, nix/overlays.nix, src/core/PortalManager.cpp, src/core/PortalManager.hpp, src/dbusDefines.hpp, src/helpers/MiscFunctions.cpp, src/portals/GlobalShortcuts.cpp, src/portals/GlobalShortcuts.hpp, src/portals/Screencopy.cpp, src/portals/Screencopy.hpp, src/portals/Screenshot.cpp, src/portals/Screenshot.hpp, src/shared/Session.cpp
Works, needs testing. Screencopy seems to be doin good
@fufexan ci
=> core: move to sdbus-cpp2

src/portals/Screencopy.cpp
I think this line might have accidentally been removed in the sdbus 2.0 migration PR after I added it back in the screensharing windows worked fine for me.
=> Readded call to toplevel activate function in onCreateSession

flake.nix, nix/default.nix, nix/overlays.nix
In the default overlay, override XDPH's package arguments to say that `sdbus-cpp = sdbus-cpp_2` which was introduced in a prior commit.
Let's discuss in #286.
This PR is my preference, until we do more digging in Nixpkgs to see if `sdbus-cpp_2` is a permanent name, or if they're phasing it out once other package updates are merged.
=> nix: overlays: xdph: override sdbus with sdbus-cpp_2 (closes #286)

.gitignore
- gitignore: add nix result and result-man
TODO:
- What is `.cache` from, and can it go under any of the existing sections as labeled in comments?
- Should `hyprland-share-picker/build` be moved under the `# build folder` section?
- Can I name the `protocols/*.{c,h}*` patterns as `# generated code`?
=> gitignore: add nix result and result-man

nix/overlays.nix
- remove `mkJoinedOverlays` function
- remove needless `with`
- change composition order (and add a comment)
=> housekeeping: nix/overlays.nix (closes #285)

nix/overlays.nix
Follow up to https://github.com/hyprwm/Hyprland/pull/8738
Moves nix overlay build to gcc14 so we can update flake in hyprland to fix it there.
=> nix/overlays: gcc13 -> gcc14

src/portals/GlobalShortcuts.cpp
The D-Bus call for ListShortcuts flat out fails/doesn't work in any scenario.
The spec states, and testing confirms, that the implementation has [requestHandle *then* sessionHandle passed](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.impl.portal.GlobalShortcuts.html#org-freedesktop-impl-portal-globalshortcuts-listshortcuts). This is the same for all other implemented methods, including the ones in this very file.
This code is entirely untested and has been brought to you by the GitHub web editor, though the issue is very obvious and my experimentation with a spec-conforming XDG portal D-Bus client confirms the issue.
As an aside, I suspect (but haven't confirmed because of this simple issue breaking my test case I am too lazy to fix for this simple issue) there …
=> Fix inverted arguments in CGlobalShortcutsPortal::onListShortcuts

src/shared/ToplevelMappingManager.cpp
Fixes #334 (`no matching function for call to 'erase_if'`) on llvm/musl
=> shared: include vector header
